### PR TITLE
Fix for issues #1 & #4

### PR DESCRIPTION
**Pull request by poldy**
I think this is a fix for issue #1. As I said, I'm not a Lisp expert so if I've got something wrong please say.

### CODE REVIEW

**Comment by poldy** [comment]
Added a proposed fix for #4 too, but it could do with a code review.

**Review by ruricolist — CHANGES_REQUESTED** [review]
What's the problem with div?

FYI, there's an easier way to return just the first value from a form: just wrap it in `values`.

    (values (cl:floor z1 z2))

**Review by ruricolist — COMMENTED** [review]
For someone who is not a Lisp expert, you put your finger on the problem. Types and classes are mostly, but not perfectly, integrated in CL. Normally, when you evaluate `defclass`, it both defines a class and defines a type with the same name. But the original author of Core Lisp used `setf` of `find-class` to directly copy the CL classes to their Core Lisp equivalents. When you do it that way (e.g. `(setf (find-class '<number>) (find-class 'cl:number))`, no type is defined.

**Review by ruricolist — APPROVED** [review]
This is right. I fixed exactly the same problem with `defglobal` and `defconstant` in 0d21119, but I missed defun.

**Pull request merged**
